version: "3.7"

services:
  api:
    image: mehdihadeli/game.services.api-gateway:dev
    container_name: api
    restart: always
    ports:
      - 7000:7000
    networks:
      - game

  messaging-service:
    image: mehdihadeli/game.services.messaging:dev
    container_name: game-messaging-service
    restart: always
    ports:
      - 7002:7002 
    networks:
      - game

  event-processor-service:
    image: mehdihadeli/game.services.event-processor:dev
    container_name: game-event-processor-service
    restart: always
    ports:
      - 7001:7001
    networks:
      - game

networks:
  game:
    name: game-network
    external: true