language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build-micro-bootstrap.sh
  - ./scripts/dotnet-build-event-processcor-service.sh
  - ./scripts/dotnet-build-messaging-service.sh
after_success:
  - ./scripts/dotnet-pack-micro-bootstrap.sh
  - ./scripts/dotnet-publish-event-processcor-service.sh
  - ./scripts/dotnet-publish-messaging-service.sh
  - ./scripts/docker-publish-event-processor-service.sh
  - ./scripts/docker-publish-messaging-service.sh
notifications:
  email:
    on_success: never
    on_failure: always