language: csharp
mono: none
sudo: required
dist: xenial
os: linux
dotnet: 6.0
branches:
  only:
    - main
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build-micro-bootstrap.sh

notifications:
  email:
    on_success: never
    on_failure: always