language: csharp
mono: none
sudo: required
dist: xenial
os: linux
dotnet: 3.1
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build-micro-bootstrap.sh
  - ./scripts/dotnet-build-event-processcor-service.sh
  - ./scripts/dotnet-build-messaging-service.sh
  - ./scripts/dotnet-build-api-gateway.sh

notifications:
  email:
    on_success: never
    on_failure: always