apiVersion: apps/v1
kind: Deployment
metadata:
    name: consul-dpl
spec:
  replicas: 1
  selector:
      matchLabels:
        name: consul
  template:
    metadata:
      labels:
        name: consul
        game-network: "true"
    spec:
      containers:
      - image: consul
        imagePullPolicy: IfNotPresent
        name: consul
        ports:
        - containerPort: 8500
      restartPolicy: Always
      volumes: null
