apiVersion: apps/v1
kind: Deployment
metadata:
 name: fabio-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fabio
  strategy: {}
  template:
    metadata:
      labels:
        name: fabio
        game-network: "true"
    spec:
      containers:
      - env:
        - name: FABIO_REGISTRY_CONSUL_ADDR
          value: consul:8500
        image: fabiolb/fabio
        imagePullPolicy: IfNotPresent
        name: fabio
        ports:
        - containerPort: 9998
        - containerPort: 9999
      restartPolicy: Always
      volumes: null
