apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jaeger
  strategy: {}
  template:
    metadata:
      labels:
        name: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one
        imagePullPolicy: IfNotPresent
        name: jaeger
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 9411
        - containerPort: 14268
        - containerPort: 16686
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
