apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo
      restartPolicy: Always
      volumes:
      - name: mongo
        persistentVolumeClaim:
          claimName: mongo
status: {}
