apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus
  strategy: {}
  template:
    metadata:
      labels:
       name: prometheus
    spec:
      containers:
      - image: prometheus
        imagePullPolicy: IfNotPresent
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
      restartPolicy: Always
      volumes: null
