apiVersion: apps/v1
kind: Deployment
metadata:
 name: seq-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: seq
  strategy: {}
  template:
    metadata:
      labels:
        name: seq
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: Y
        image: datalust/seq
        imagePullPolicy: IfNotPresent
        name: seq
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
