apiVersion: apps/v1
kind: Deployment
metadata:
 name: vault-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault
  strategy: {}
  template:
    metadata:
      labels:
        name: vault
    spec:
      containers:
      - env:
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: secret
        image: vault
        imagePullPolicy: IfNotPresent
        name: vault
        ports:
        - containerPort: 8200
        resources: {}
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
