apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dpl
spec:
  replicas: 1
  selector:
      matchLabels:
        name: api
  template:
    metadata:
      labels:
       name: api
    spec:
      containers:
      - image: mehdihadeli/game.services.api-gateway
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 7000
      restartPolicy: Always
      volumes: null
