apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor-service-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
        name: event-processor-service
  strategy: {}
  template:
    metadata:
      labels:
       name: event-processor-service
    spec:
      containers:
      - image: mehdihadeli/game.services.event-processor
        imagePullPolicy: IfNotPresent
        name: event-processor-service
        ports:
        - containerPort: 7001
      restartPolicy: Always
      volumes: null
