apiVersion: v1
kind: Service
metadata:
 name: event-processor-service-svc
 labels:
    name: event-processor-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 7001
    targetPort: 7001
  selector:
    name: event-processor-service
