apiVersion: v1
kind: Service
metadata:
  name: messaging-service-svc
  labels:
    name: messaging-service
spec:
  type: NodePort
  ports:
  - name: "7002"
    port: 7002
    targetPort: 7002
  selector:
    name: messaging-service
