apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
        name: messaging-service
  strategy: {}
  template:
    metadata:
      labels:
       name: messaging-service
    spec:
      containers:
      - image: mehdihadeli/game.services.messaging
        imagePullPolicy: IfNotPresent
        name: messaging-service
        ports:
        - containerPort: 7002
        resources: {}
      restartPolicy: Always
      volumes: null
