name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: accesst to files
      run: chmod -R a+x scripts
      
    - name: dotnet-build-micro-bootstrap
      run: ./scripts/dotnet-build-micro-bootstrap.sh
    
    - name: dotnet-build-event-processcor-service
      run: ./scripts/dotnet-build-event-processcor-service.sh
      
    - name: dotnet-build-messaging-service
      run:  ./scripts/dotnet-build-messaging-service.sh
      
    - name: dotnet-build-api-gateway
      run: ./scripts/dotnet-build-api-gateway.sh
    - name : pack
      run: ./scripts/dotnet-pack-micro-bootstrap.sh
