name: Publish Source Artifact

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Save src folder
      uses: actions/upload-artifact@v2
      with:
        name: source
        path: src
        
    - name: Download files to publish
      uses: actions/download-artifact@v2
      with:
        name: source
